@props(['benefits' => []])
<section class="bg-white py-16 sm:py-20 lg:py-24">
    <div class="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:gap-16 lg:px-8">
        <div><p class="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">For suppliers and manufacturers</p><h2 class="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Grow Your Business With Future Line Trading</h2><p class="mt-5 max-w-xl text-base leading-7 text-slate-600">Reach verified buyers, showcase your products and build trusted business relationships through our B2B marketplace.</p>
            <div class="mt-7 grid gap-3 sm:grid-cols-2">@foreach ($benefits as $benefit)<div class="flex items-center gap-3 border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold text-slate-700"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg></span>{{ $benefit }}</div>@endforeach</div>
            <div class="mt-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><a href="{{ route('register') }}" class="inline-flex w-full items-center justify-center bg-emerald-700 px-5 py-3 text-sm font-bold text-white shadow-sm transition-colors hover:bg-emerald-800 sm:w-auto">Become a Seller</a><a href="{{ route('about') }}" class="text-sm font-bold text-emerald-700 hover:text-emerald-800">Learn More About Selling</a></div>
        </div>
        <div class="relative mx-auto w-full max-w-xl"><div class="absolute -left-4 -top-4 hidden h-32 w-32 border border-emerald-200 bg-emerald-50 lg:block"></div><div class="relative overflow-hidden border border-slate-200 bg-white p-2 shadow-xl shadow-emerald-950/10"><img src="{{ frontend_image('business_cta.seller') }}" alt="Agricultural supplier supporting the marketplace" loading="lazy" decoding="async" class="h-72 w-full object-cover sm:h-96"><div class="absolute bottom-6 left-6 border border-white/70 bg-white/95 p-4 shadow-lg"><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Built for business growth</p><p class="mt-1 text-lg font-bold text-slate-950">Showcase. Connect. Trade.</p></div></div></div>
    </div>
</section>
