@extends('layouts.dashboard')

@section('title', 'Buyer Dashboard')

@section('content')
@php
    $orders = [
        ['id' => '#FLT-10245', 'product' => 'Premium Pangas Fish Feed', 'seller' => 'Green Feed Industries', 'quantity' => '500 KG', 'amount' => '৳27,500', 'status' => 'Processing', 'date' => '12 Sep 2026'],
        ['id' => '#FLT-10231', 'product' => 'Tilapia Floating Feed', 'seller' => 'Bluewater Feeds', 'quantity' => '300 KG', 'amount' => '৳15,600', 'status' => 'Seller Confirmed', 'date' => '10 Sep 2026'],
        ['id' => '#FLT-10198', 'product' => 'Soybean Meal', 'seller' => 'Global Agro Trading', 'quantity' => '1,000 KG', 'amount' => '৳65,000', 'status' => 'Advance Paid', 'date' => '06 Sep 2026'],
        ['id' => '#FLT-10172', 'product' => 'Dairy Cattle Feed', 'seller' => 'DeltaFeed', 'quantity' => '750 KG', 'amount' => '৳31,500', 'status' => 'Ready for Delivery', 'date' => '02 Sep 2026'],
        ['id' => '#FLT-10126', 'product' => 'Broiler Starter Feed', 'seller' => 'RoyalMix', 'quantity' => '500 KG', 'amount' => '৳30,500', 'status' => 'Completed', 'date' => '28 Aug 2026'],
    ];
    $wishlist = [
        ['name' => 'Premium Pangas Fish Feed', 'slug' => 'premium-pangas-fish-feed', 'brand' => 'GreenLine', 'grade' => 'Grade 1', 'seller' => 'Green Feed Industries', 'location' => 'Dhaka, Bangladesh', 'price' => '৳55 / KG', 'priceTon' => '৳55,000', 'moq' => '500 KG', 'rating' => '4.8', 'stock' => 'In Stock', 'image' => config('frontend-images.products.premium_pangas')],
        ['name' => 'Shrimp Feed Premium', 'slug' => 'shrimp-feed-premium', 'brand' => 'CoastalFeed', 'grade' => 'Grade 1', 'seller' => 'Coastal Feed Mills', 'location' => 'Chattogram, Bangladesh', 'price' => '৳78 / KG', 'priceTon' => '৳78,000', 'moq' => '300 KG', 'rating' => '4.9', 'stock' => 'In Stock', 'image' => config('frontend-images.products.shrimp_premium')],
        ['name' => 'Soybean Meal', 'slug' => 'soybean-meal', 'brand' => 'MarineSource', 'grade' => 'Feed Grade', 'seller' => 'Global Agro Trading', 'location' => 'Chattogram, Bangladesh', 'price' => '৳65 / KG', 'priceTon' => '৳65,000', 'moq' => '1,000 KG', 'rating' => '4.7', 'stock' => 'In Stock', 'image' => config('frontend-images.products.soybean_meal')],
        ['name' => 'Dairy Cattle Feed', 'slug' => 'dairy-cattle-feed', 'brand' => 'DeltaFeed', 'grade' => 'Grade 1', 'seller' => 'Delta Nutrition Ltd.', 'location' => 'Gazipur, Bangladesh', 'price' => '৳42 / KG', 'priceTon' => '৳42,000', 'moq' => '1,000 KG', 'rating' => '4.8', 'stock' => 'In Stock', 'image' => config('frontend-images.products.dairy_cattle')],
    ];
    $recommended = [
        ['name' => 'Tilapia Floating Feed', 'slug' => 'tilapia-floating-feed', 'brand' => 'AquaPlus', 'grade' => 'Grade 1', 'seller' => 'Bluewater Feeds', 'location' => 'Khulna, Bangladesh', 'price' => '৳52 / KG', 'priceTon' => '৳52,000', 'moq' => '500 KG', 'rating' => '4.7', 'stock' => 'In Stock', 'image' => config('frontend-images.products.tilapia_floating')],
        ['name' => 'Layer Feed Premium', 'slug' => 'layer-feed', 'brand' => 'GoldenGrain', 'grade' => 'Grade 1', 'seller' => 'Bengal Agro Foods', 'location' => 'Gazipur, Bangladesh', 'price' => '৳49 / KG', 'priceTon' => '৳49,000', 'moq' => '500 KG', 'rating' => '4.7', 'stock' => 'In Stock', 'image' => config('frontend-images.products.layer_feed')],
        ['name' => 'Fish Meal', 'slug' => 'fish-meal', 'brand' => 'MarineSource', 'grade' => 'Grade 1', 'seller' => 'Green Feed Industries', 'location' => 'Dhaka, Bangladesh', 'price' => '৳112 / KG', 'priceTon' => '৳112,000', 'moq' => '500 KG', 'rating' => '4.8', 'stock' => 'In Stock', 'image' => config('frontend-images.products.fish_meal')],
        ['name' => 'Broiler Starter Feed', 'slug' => 'broiler-starter-feed', 'brand' => 'RoyalMix', 'grade' => 'Grade 1', 'seller' => 'Prime Feed Industries', 'location' => 'Rajshahi, Bangladesh', 'price' => '৳61 / KG', 'priceTon' => '৳61,000', 'moq' => '500 KG', 'rating' => '4.6', 'stock' => 'In Stock', 'image' => config('frontend-images.products.broiler_starter')],
    ];
@endphp

<x-dashboard-header title="Dashboard" breadcrumb="Buyer Account / Overview" />

<div class="mx-auto max-w-[1320px] space-y-7 p-4 sm:p-6 lg:p-8">
    <section class="border border-emerald-200 bg-emerald-950 px-5 py-6 text-white shadow-lg shadow-emerald-950/10 sm:px-7 sm:py-7">
        <div class="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><span class="inline-flex items-center gap-1.5 border border-emerald-400/40 bg-emerald-900/60 px-2.5 py-1 text-xs font-bold text-emerald-100"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg> Verified Buyer</span><h2 class="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">Welcome back, Mohammad</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-emerald-50/80">Track your purchases, discover products and manage your business activity.</p></div><div class="flex flex-col gap-3 sm:flex-row"><a href="{{ route('products.index') }}" class="inline-flex items-center justify-center bg-white px-4 py-3 text-sm font-bold text-emerald-900 transition hover:bg-emerald-50">Explore Products</a><a href="#orders" class="inline-flex items-center justify-center border border-emerald-300/70 px-4 py-3 text-sm font-bold text-white transition hover:bg-emerald-900">View Orders</a></div></div>
    </section>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card value="24" label="Total Orders" detail="All purchase records" icon="orders" /><x-stat-card value="3" label="Pending Orders" detail="Needs your attention" icon="clock" tone="amber" /><x-stat-card value="18" label="Completed Orders" detail="Successfully completed" icon="check" tone="sky" /><x-stat-card value="12" label="Wishlist" detail="Products saved for later" icon="heart" tone="rose" /></section>

    <section id="orders" class="border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-3 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-950">Recent Orders</h2><p class="mt-1 text-sm text-slate-500">Your latest marketplace purchases and status updates.</p></div><a href="#" class="text-sm font-bold text-emerald-700 hover:text-emerald-800">View all orders →</a></div><div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Order ID</th><th class="px-5 py-3">Product</th><th class="px-5 py-3">Seller</th><th class="px-5 py-3">Quantity</th><th class="px-5 py-3">Amount</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Date</th><th class="px-5 py-3">Action</th></tr></thead><tbody>@foreach($orders as $order)<x-order-row :order="$order" />@endforeach</tbody></table></div></section>

    <div class="grid gap-7 xl:grid-cols-[1.35fr_.65fr]">
        <section id="tracking" class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Active order</p><h2 class="mt-1 text-lg font-bold text-slate-950">Order Tracking</h2><p class="mt-1 text-sm text-slate-600"><span class="font-bold text-slate-800">#FLT-10245</span> · Premium Pangas Fish Feed · 500 KG</p></div><x-order-status-badge status="Processing" /></div><div class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Order Placed', 'Payment Pending', 'Advance Paid', 'Seller Confirmed', 'Processing', 'Ready for Delivery', 'Shipped', 'Delivered'] as $index => $step)<div class="relative flex gap-3 sm:block"><span @class(['flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-xs font-bold sm:mx-auto', 'border-emerald-700 bg-emerald-700 text-white' => $index < 5, 'border-slate-300 bg-white text-slate-400' => $index >= 5])>{{ $index < 5 ? '✓' : $index + 1 }}</span><div class="sm:mt-3 sm:text-center"><p @class(['text-xs font-bold uppercase tracking-wide', 'text-emerald-800' => $index === 4, 'text-slate-700' => $index < 4, 'text-slate-400' => $index > 4])>{{ $step }}</p>@if($index === 4)<p class="mt-1 text-xs font-medium text-emerald-700">Current status</p>@endif</div></div>@endforeach</div></section>
        <section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Account &amp; Verification</h2><p class="mt-1 text-sm text-slate-500">Your buyer account at a glance.</p><div class="mt-5"><div class="flex justify-between text-sm"><span class="font-semibold text-slate-700">Profile Completion</span><span class="font-bold text-emerald-700">85%</span></div><div class="mt-2 h-2 bg-slate-100"><span class="block h-2 w-[85%] bg-emerald-600"></span></div></div><dl class="mt-6 space-y-3 text-sm">@foreach(['Business Verification' => 'Verified', 'Mobile' => 'Verified', 'Email' => 'Verified'] as $label => $value)<div class="flex items-center justify-between gap-3 border-b border-slate-100 pb-3"><dt class="text-slate-600">{{ $label }}</dt><dd class="inline-flex items-center gap-1 font-bold text-emerald-700"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg>{{ $value }}</dd></div>@endforeach</dl><div class="mt-6 grid grid-cols-2 gap-3"><a href="#" class="inline-flex items-center justify-center border border-emerald-700 px-3 py-2.5 text-xs font-bold text-emerald-800 hover:bg-emerald-50">Complete Profile</a><a href="#" class="inline-flex items-center justify-center border border-slate-300 px-3 py-2.5 text-xs font-bold text-slate-700 hover:border-emerald-600">View Verification</a></div></section>
    </div>

    <section><div class="mb-4 flex items-end justify-between gap-4"><div><h2 class="text-xl font-bold tracking-tight text-slate-950">Your Wishlist</h2><p class="mt-1 text-sm text-slate-500">Products you have saved for a future order.</p></div><a href="#" class="whitespace-nowrap text-sm font-bold text-emerald-700 hover:text-emerald-800">View All Wishlist →</a></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($wishlist as $product)<x-product-card :product="$product" />@endforeach</div></section>

    <section><div class="mb-4"><h2 class="text-xl font-bold tracking-tight text-slate-950">Recommended For You</h2><p class="mt-1 text-sm text-slate-500">Selected from your demo buyer interests and previous orders.</p></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($recommended as $product)<x-product-card :product="$product" />@endforeach</div></section>

    <div class="grid gap-7 lg:grid-cols-2"><section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Recent Activity</h2><div class="relative mt-6 before:absolute before:bottom-4 before:left-[13px] before:top-4 before:w-px before:bg-slate-200"><x-activity-item title="Order #FLT-10245 confirmed" detail="Green Feed Industries confirmed your feed order." time="Today, 10:24 AM" /><x-activity-item title="Payment proof submitted" detail="A demo payment proof was attached to #FLT-10198." time="Yesterday, 4:15 PM" tone="sky" /><x-activity-item title="Seller responded to your enquiry" detail="Bluewater Feeds replied about available tilapia feed." time="10 Sep 2026" tone="violet" /><x-activity-item title="Review submitted" detail="Your review for Dairy Cattle Feed is now visible." time="08 Sep 2026" tone="amber" /><x-activity-item title="Product added to wishlist" detail="Shrimp Feed Premium was saved for later." time="07 Sep 2026" tone="rose" /></div></section><section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Quick Actions</h2><p class="mt-1 text-sm text-slate-500">Start common buyer tasks from one place.</p><div class="mt-5 grid gap-3 sm:grid-cols-2"><x-quick-action label="Search Products" :href="route('products.index')" icon="search" /><x-quick-action label="Track Order" href="#tracking" icon="truck" /><x-quick-action label="View Cart" :href="route('products.index')" icon="cart" /><x-quick-action label="Message Seller" href="#" icon="message" /><x-quick-action label="Request a Quote" href="#" icon="quote" /></div><div class="mt-6 border-l-2 border-emerald-600 bg-emerald-50 px-4 py-3"><p class="text-sm font-bold text-emerald-900">Demo workspace</p><p class="mt-1 text-xs leading-5 text-emerald-800">All account details, activity, order status, and actions shown here are static frontend demo data.</p></div></section></div>
</div>
@endsection
