@extends('layouts.seller-dashboard')

@section('title', 'Seller Dashboard')

@section('content')
@php
    $orders = [
        ['id'=>'#FLT-10245','buyer'=>'Rahman Agro Farm','product'=>'Premium Pangas Fish Feed','quantity'=>'500 KG','amount'=>'৳27,500','payment'=>'Advance Paid','status'=>'Processing','date'=>'12 Sep 2026'],
        ['id'=>'#FLT-10238','buyer'=>'Karim Fish Farm','product'=>'Tilapia Floating Feed','quantity'=>'300 KG','amount'=>'৳15,600','payment'=>'Payment Pending','status'=>'Seller Confirmed','date'=>'11 Sep 2026'],
        ['id'=>'#FLT-10212','buyer'=>'M/S Noor Traders','product'=>'Shrimp Feed Premium','quantity'=>'250 KG','amount'=>'৳19,500','payment'=>'Advance Paid','status'=>'Ready for Delivery','date'=>'08 Sep 2026'],
        ['id'=>'#FLT-10196','buyer'=>'Sarker Dairy Farm','product'=>'Dairy Cattle Feed','quantity'=>'1,000 KG','amount'=>'৳42,000','payment'=>'Advance Paid','status'=>'Shipped','date'=>'05 Sep 2026'],
        ['id'=>'#FLT-10164','buyer'=>'Al Amin Poultry','product'=>'Broiler Starter Feed','quantity'=>'500 KG','amount'=>'৳30,500','payment'=>'Advance Paid','status'=>'Completed','date'=>'01 Sep 2026'],
    ];
    $products = [
        ['Premium Pangas Fish Feed','68','12,500 KG','৳687,500','4.9','Active'], ['Tilapia Floating Feed','54','9,800 KG','৳509,600','4.8','Active'], ['Dairy Cattle Feed','43','7,200 KG','৳302,400','4.8','Active'], ['Broiler Starter Feed','39','6,000 KG','৳366,000','4.7','Active'], ['Shrimp Feed Premium','31','4,400 KG','৳343,200','4.9','Active'],
    ];
@endphp

<x-seller-header />
<div class="mx-auto max-w-[1320px] space-y-7 p-4 sm:p-6 lg:p-8">
    <section class="border border-emerald-200 bg-emerald-950 px-5 py-6 text-white shadow-lg shadow-emerald-950/10 sm:px-7 sm:py-7"><div class="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><span class="inline-flex items-center gap-1.5 border border-emerald-400/40 bg-emerald-900/60 px-2.5 py-1 text-xs font-bold text-emerald-100"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg> Verified Business</span><h2 class="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">Welcome back, Green Feed Industries</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-emerald-50/80">Manage your products, orders, customers and marketplace activity.</p><div class="mt-4 flex flex-wrap gap-2"><span class="border border-emerald-400/40 px-2.5 py-1 text-xs font-bold text-emerald-100">Business Status: ACTIVE</span><span class="border border-emerald-400/40 px-2.5 py-1 text-xs font-bold text-emerald-100">Product Status: APPROVED</span></div></div><div class="flex flex-col gap-3 sm:flex-row"><a href="#inventory" class="inline-flex items-center justify-center bg-white px-4 py-3 text-sm font-bold text-emerald-900 hover:bg-emerald-50">Add New Product</a><a href="{{ route('products.index') }}" class="inline-flex items-center justify-center border border-emerald-300/70 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-900">View Marketplace</a></div></div></section>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><x-seller-stat-card value="120" label="Total Products" detail="All catalogue listings" /><x-seller-stat-card value="108" label="Active Products" detail="Available to buyers" /><x-seller-stat-card value="8" label="Pending Orders" detail="Require order attention" icon="orders" /><x-seller-stat-card value="৳1,850,000" label="Total Sales" detail="Demo sales value" icon="sales" /><x-seller-stat-card value="৳245,000" label="Pending Settlement" detail="Demo payable amount" icon="wallet" /><x-seller-stat-card value="356" label="Customer Reviews" detail="Feedback received" icon="star" /></section>

    <section class="grid gap-7 xl:grid-cols-[1.35fr_.65fr]"><div class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-950">Sales Overview</h2><p class="mt-1 text-sm text-slate-500">Monthly sales performance using frontend demo values.</p></div><span class="border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-bold text-slate-600">Jan – Jun 2026</span></div><x-sales-chart :values="[180, 240, 210, 310, 285, 360]" /></div><div class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Sales Summary</h2><p class="mt-1 text-sm text-slate-500">Current demo reporting period.</p><dl class="mt-6 space-y-4">@foreach(['Total Sales'=>'৳1,850,000','Orders'=>'248','Units Sold'=>'32,500 KG'] as $label=>$value)<div class="flex items-end justify-between border-b border-slate-100 pb-3"><dt class="text-sm font-semibold text-slate-600">{{ $label }}</dt><dd class="text-lg font-bold text-slate-950">{{ $value }}</dd></div>@endforeach</dl><p class="mt-5 border-l-2 border-emerald-600 bg-emerald-50 px-3 py-2 text-xs leading-5 text-emerald-800">These figures are static dashboard examples and do not represent a live sales calculation.</p></div></section>

    <section class="border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-3 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-950">Recent Orders</h2><p class="mt-1 text-sm text-slate-500">Latest buyer orders received by your business.</p></div><a href="#" class="text-sm font-bold text-emerald-700">View all orders →</a></div><div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-left"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Order ID</th><th class="px-5 py-3">Buyer</th><th class="px-5 py-3">Product</th><th class="px-5 py-3">Quantity</th><th class="px-5 py-3">Amount</th><th class="px-5 py-3">Payment</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Date</th><th class="px-5 py-3">Action</th></tr></thead><tbody>@foreach($orders as $order)<x-seller-order-row :order="$order" />@endforeach</tbody></table></div></section>

    <section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-950">Top Performing Products</h2><p class="mt-1 text-sm text-slate-500">Product performance based on static marketplace demo records.</p></div><a href="#" class="text-sm font-bold text-emerald-700">Manage products →</a></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="border-b border-slate-200 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="pb-3">Product</th><th class="pb-3">Orders</th><th class="pb-3">Quantity Sold</th><th class="pb-3">Revenue</th><th class="pb-3">Rating</th><th class="pb-3">Status</th></tr></thead><tbody>@foreach($products as [$name,$ordersCount,$quantity,$revenue,$rating,$status])<tr class="border-b border-slate-100"><td class="py-4 font-bold text-slate-800">{{ $name }}</td><td class="py-4 text-slate-600">{{ $ordersCount }} Orders</td><td class="py-4 text-slate-600">{{ $quantity }}</td><td class="py-4 font-semibold text-slate-900">{{ $revenue }}</td><td class="py-4 font-bold text-amber-600">{{ $rating }} ★</td><td class="py-4"><span class="border border-emerald-100 bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-800">{{ $status }}</span></td></tr>@endforeach</tbody></table></div></section>

    <section id="inventory" class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-950">Inventory Overview</h2><p class="mt-1 text-sm text-slate-500">Static inventory indicators to help organize product availability.</p></div><div class="flex gap-3"><a href="#" class="border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 hover:border-emerald-600">Manage Products</a><a href="#" class="bg-emerald-700 px-3 py-2 text-sm font-bold text-white hover:bg-emerald-800">Add Product</a></div></div><div class="mt-5 grid gap-3 grid-cols-2 lg:grid-cols-4"><x-inventory-status label="In Stock" value="94" /><x-inventory-status label="Low Stock" value="8" tone="amber" /><x-inventory-status label="Out of Stock" value="3" tone="rose" /><x-inventory-status label="Pending Approval" value="15" tone="sky" /></div><div class="mt-6 overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b border-slate-200 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="pb-3">Product</th><th class="pb-3">Stock</th><th class="pb-3">Unit</th><th class="pb-3">Status</th><th class="pb-3">Action</th></tr></thead><tbody>@foreach([['Premium Pangas Fish Feed','18,500','KG','In Stock'],['Tilapia Floating Feed','2,400','KG','Low Stock'],['Shrimp Feed Premium','0','KG','Out of Stock'],['Dairy Cattle Feed','12,000','KG','In Stock']] as [$name,$stock,$unit,$status])<tr class="border-b border-slate-100"><td class="py-4 font-bold text-slate-800">{{ $name }}</td><td class="py-4 text-slate-600">{{ $stock }}</td><td class="py-4 text-slate-600">{{ $unit }}</td><td class="py-4"><span @class(['border px-2 py-1 text-xs font-bold','border-emerald-100 bg-emerald-50 text-emerald-800'=>$status==='In Stock','border-amber-100 bg-amber-50 text-amber-800'=>$status==='Low Stock','border-rose-100 bg-rose-50 text-rose-800'=>$status==='Out of Stock'])>{{ $status }}</span></td><td class="py-4"><a href="#" class="font-bold text-emerald-700">Update</a></td></tr>@endforeach</tbody></table></div></section>

    <x-settlement-summary />

    <div class="grid gap-7 xl:grid-cols-[1.1fr_.9fr]"><section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Recent Customer Activity</h2><div class="relative mt-6 before:absolute before:bottom-4 before:left-[13px] before:top-4 before:w-px before:bg-slate-200"><x-activity-item title="Rahman Agro Farm placed an order" detail="New order #FLT-10245 for Premium Pangas Fish Feed." time="Today, 10:24 AM" /><x-activity-item title="Karim Fish Farm sent a message" detail="Buyer asked about the next available feed batch." time="Today, 9:10 AM" tone="sky" /><x-activity-item title="Buyer requested a quotation" detail="A demo quotation request was received for bulk dairy feed." time="Yesterday, 4:30 PM" tone="violet" /><x-activity-item title="New review received" detail="Rahman Agro Farm left a 5.0-star verified purchase review." time="Yesterday, 1:15 PM" tone="amber" /><x-activity-item title="Order #FLT-10245 was confirmed" detail="The buyer's advance payment was marked as received in this demo view." time="12 Sep 2026" tone="rose" /></div></section><section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Business Verification</h2><p class="mt-1 text-sm text-slate-500">Business profile details shown as frontend demo indicators.</p><span class="mt-5 inline-flex items-center gap-1.5 border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-sm font-bold text-emerald-800"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg> VERIFIED</span><ul class="mt-5 space-y-3">@foreach(['Business Profile','Contact Information','Business Documents','Product Information'] as $item)<li class="flex items-center gap-3 border-b border-slate-100 pb-3 text-sm font-semibold text-slate-700"><span class="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-100 text-emerald-700">✓</span>{{ $item }}</li>@endforeach</ul><a href="#" class="mt-6 inline-flex w-full items-center justify-center border border-emerald-700 px-4 py-2.5 text-sm font-bold text-emerald-800 hover:bg-emerald-50">View Verification</a><div class="mt-6 border-t border-slate-200 pt-5"><div class="flex items-center justify-between"><h3 class="font-bold text-slate-900">Seller Notifications</h3><a href="#" class="text-xs font-bold text-emerald-700">View All Notifications</a></div><ul class="mt-3 space-y-2">@foreach(['Your product was approved.','New order received.','Payment proof uploaded.','Buyer sent a message.','New review received.'] as $notification)<li class="flex gap-2 text-sm text-slate-600"><span class="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-600"></span>{{ $notification }}</li>@endforeach</ul></div></section></div>

    <x-review-summary />
    <section class="border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-950">Quick Actions</h2><p class="mt-1 text-sm text-slate-500">Common seller tasks in one professional workspace.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><x-quick-action label="Add Product" href="#inventory" icon="quote" /><x-quick-action label="Manage Orders" href="#" icon="truck" /><x-quick-action label="View Messages" href="#" icon="message" /><x-quick-action label="Update Business Profile" href="#" icon="quote" /><x-quick-action label="View Reports" href="#" icon="quote" /><x-quick-action label="Contact Support" href="#" icon="message" /></div></section>
</div>
@endsection
