@extends('layouts.app')

@section('title', 'Explore Product Categories')

@section('content')
@php
    $categories = [
        ['name'=>'Fish Feed','description'=>'Specialized nutrition for commercial fish farms and aquaculture operations.','count'=>'148','subcategories'=>['Pangas','Tilapia','Shrimp','Shing','Magur','Pabda','Gulsha','Tengra','Other Fish Feed'],'image'=>config('frontend-images.categories.fish_feed')],
        ['name'=>'Cattle Feed','description'=>'Balanced feed solutions for dairy, beef cattle and healthy calf growth.','count'=>'96','subcategories'=>['Dairy','Beef Cattle','Calf','Other Cattle Feed'],'image'=>config('frontend-images.categories.cattle_feed')],
        ['name'=>'Poultry Feed','description'=>'Reliable poultry nutrition for broiler, layer and chick operations.','count'=>'124','subcategories'=>['Broiler','Layer','Chick','Other Poultry Feed'],'image'=>config('frontend-images.categories.poultry_feed')],
        ['name'=>'Duck Feed','description'=>'Feed ranges made for every stage of productive duck farming.','count'=>'42','subcategories'=>['Starter','Grower','Layer','Other Duck Feed'],'image'=>config('frontend-images.categories.duck_feed')],
        ['name'=>'Animal Feed','description'=>'Everyday feed support for goat, sheep and other animal farms.','count'=>'58','subcategories'=>['Goat','Sheep','Other Animal Feed'],'image'=>config('frontend-images.categories.animal_feed')],
        ['name'=>'Feed Raw Materials','description'=>'Essential ingredients for dependable feed formulation and production.','count'=>'187','subcategories'=>['Fish Meal','Soybean Meal','Maize','Rice Polish','Rice Bran','Wheat Bran','DDGS','DORB','CGM','Fish Oil','Premix','Limestone','Mustard Oil Cake','Mineral Mixture','Protein Ingredients'],'image'=>config('frontend-images.categories.raw_materials')],
    ];
    $popular = array_values(array_filter($categories, fn ($category) => in_array($category['name'], ['Fish Feed', 'Cattle Feed', 'Poultry Feed', 'Feed Raw Materials'])));
@endphp

<section class="border-b border-slate-200 bg-white"><div class="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><x-breadcrumb :items="['Categories']" /><div class="mt-5 max-w-3xl"><p class="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Marketplace catalogue</p><h1 class="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Explore Product Categories</h1><p class="mt-4 text-base leading-7 text-slate-600">Find feed, ingredients and raw materials from trusted businesses across the Future Line Trading marketplace.</p></div><div class="relative mt-8 max-w-3xl"><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg><input type="search" data-category-search-input placeholder="Search categories..." class="w-full border border-slate-300 bg-white py-3.5 pl-12 pr-4 text-sm text-slate-900 shadow-sm placeholder:text-slate-400 focus:border-emerald-600 focus:outline-none"><p data-category-empty class="mt-3 hidden text-sm font-medium text-slate-500">No matching categories found. Try a different product or ingredient.</p></div></div></section>

<section id="main-categories" class="bg-slate-50 py-12 sm:py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Browse by need</p><h2 class="mt-2 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Main Categories</h2></div><p class="max-w-md text-sm leading-6 text-slate-600">Choose a category to discover its specialist feed, raw-material and ingredient options.</p></div><div data-category-grid class="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">@foreach($categories as $category)<x-category-explorer-card :category="$category" />@endforeach</div></div></section>

<section class="border-y border-slate-200 bg-white py-12 sm:py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="max-w-2xl"><p class="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Marketplace favourites</p><h2 class="mt-2 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Popular Categories</h2><p class="mt-3 text-sm leading-6 text-slate-600">Explore frequently sourced feed and raw-material categories from the marketplace.</p></div><div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($popular as $category)<article class="group relative min-h-64 overflow-hidden border border-slate-200 bg-slate-950 shadow-sm"><img src="{{ asset($category['image']) }}" alt="{{ $category['name'] }}" loading="lazy" class="absolute inset-0 h-full w-full object-cover opacity-45 transition duration-500 group-hover:scale-105"><div class="absolute inset-0 bg-slate-950/35"></div><div class="relative flex min-h-64 flex-col justify-end p-5"><span class="w-fit border border-emerald-300/50 bg-emerald-900/50 px-2 py-1 text-xs font-bold text-emerald-100">{{ $category['count'] }} demo products</span><h3 class="mt-3 text-xl font-bold text-white">{{ $category['name'] }}</h3><p class="mt-2 text-sm leading-5 text-slate-200">{{ implode(' · ', array_slice($category['subcategories'], 0, 3)) }}</p><a href="#main-categories" class="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-200 hover:text-white">Explore Category <span>→</span></a></div></article>@endforeach</div></div></section>

<section class="bg-slate-50 py-12 sm:py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="border border-emerald-200 bg-emerald-950 p-6 text-white shadow-lg shadow-emerald-950/10 sm:p-9"><div class="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Need help sourcing?</p><h2 class="mt-3 text-2xl font-bold tracking-tight sm:text-3xl">Can’t Find What You Need?</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-emerald-50/85">Search the marketplace or contact a verified supplier for your business requirements.</p></div><div class="flex flex-col gap-3 sm:flex-row"><x-button :href="route('products.index')" class="border-white bg-white text-emerald-900 hover:bg-emerald-50">Search Products</x-button><x-button :href="route('contact')" variant="secondary" class="border-emerald-300 bg-transparent text-white hover:bg-emerald-900">Contact Us</x-button></div></div></div></div></section>
@endsection
